#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class _Templates_jsMethod_template : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden
        #line 2 "..\..\Templates\jsMethod.template"
            
  public dynamic Model { get; set; }

        #line default
        #line hidden
        
        public override void Execute()
        {
WriteLiteral("\r\n");

WriteLiteral("this.");

            
            #line 5 "..\..\Templates\jsMethod.template"
Write(Model.MethodName);

            
            #line default
            #line hidden
WriteLiteral(" = function ");

            
            #line 5 "..\..\Templates\jsMethod.template"
                             Write(Model.Arguments);

            
            #line default
            #line hidden
WriteLiteral("\r\n{\r\n\tvar deferred = $q.defer();\r\n\r\n    $http.post(");

            
            #line 9 "..\..\Templates\jsMethod.template"
          Write(Model.Path);

            
            #line default
            #line hidden
WriteLiteral(", {\r\n");

WriteLiteral("\t\t");

            
            #line 10 "..\..\Templates\jsMethod.template"
   Write(Model.Data);

            
            #line default
            #line hidden
WriteLiteral("\r\n\t}).then(function(__response) {\r\n\t\tdeferred.resolve(__response.data.__res);\r\n\t}" +
", function(ex){\r\n\t\tdeferred.reject(ex);\r\n    });\r\n\r\n    return deferred.promise;" +
"\r\n}\r\n");

        }
    }
}
#pragma warning restore 1591
