#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class _Templates_jsProperty_template : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden
        #line 2 "..\..\Templates\jsProperty.template"
            
  public dynamic Model { get; set; }

        #line default
        #line hidden
        
        public override void Execute()
        {
WriteLiteral("\r\n");

WriteLiteral("this.");

            
            #line 5 "..\..\Templates\jsProperty.template"
Write(Model.Name);

            
            #line default
            #line hidden
WriteLiteral(" = __init.");

            
            #line 5 "..\..\Templates\jsProperty.template"
                     Write(Model.Name);

            
            #line default
            #line hidden
WriteLiteral(";");

        }
    }
}
#pragma warning restore 1591
