// <auto-generated />
namespace Excess.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AddingProjects : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddingProjects));
        
        string IMigrationMetadata.Id
        {
            get { return "201501030707045_Adding-Projects"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
