// <auto-generated />
namespace Excess.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class filehash : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(filehash));
        
        string IMigrationMetadata.Id
        {
            get { return "201503110510197_filehash"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
