//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Excess.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SampleCode {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SampleCode() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Excess.Web.Resources.SampleCode", typeof(SampleCode).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to class Arrays 
        ///{
        ///    void main()
        ///    {
        ///        var arr = [10, 15, 30];
        ///        
        ///        foreach(int val in arr)
        ///            console.write(val);
        ///    }
        ///}.
        /// </summary>
        public static string Arrays {
            get {
                return ResourceManager.GetString("Arrays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to class DSL
        ///{
        ///    void main()
        ///    {
        ///        asynch()
        ///        {
        ///            var x = expensive();
        ///          	
        ///            synch()
        ///            {
        ///              	notify(x);
        ///            }
        ///        }
        ///    }
        ///}.
        /// </summary>
        public static string DSLAsynch {
            get {
                return ResourceManager.GetString("DSLAsynch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace Events 
        ///{
        ///    class Base
        ///    {
        ///        public delegate void FinishedHandler(int x, int y);
        ///        public event FinishedHandler FinishedEvent;
        ///    }
        ///  
        ///    class Derived : Base
        ///    {
        ///        public event closed(int x, int y);
        ///
        ///        on closed(x, y)
        ///        {
        ///            console.write(x);
        ///        }
        ///
        ///        on finished()
        ///        {
        ///            console.write(y);
        ///        }
        ///    }
        ///}.
        /// </summary>
        public static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to class Functions 
        ///{
        ///    void main()
        ///    {
        ///        foo(function(i){
        ///            console.write(i);
        ///            return i + 5;
        ///        });
        ///    }
        ///  
        ///    function foo(function&lt;int, int&gt; callback)
        ///    {
        ///        int result = callback(73);
        ///        return result;
        ///    }
        ///
        ///    string function bar()
        ///    {
        ///        return &quot;bar&quot;;
        ///    }
        ///}.
        /// </summary>
        public static string Functions {
            get {
                return ResourceManager.GetString("Functions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to void main()
        ///{
        ///    console.write(&quot;Hello World&quot;);
        ///}.
        /// </summary>
        public static string HelloWorld {
            get {
                return ResourceManager.GetString("HelloWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public class Lolcat
        ///{
        ///    constructor(string name)
        ///    {
        ///        Name = name;
        ///        initSpeekers();
        ///    }
        ///
        ///    string property Name;
        ///
        ///    method Say(Mood mood)
        ///    { 
        ///        Speek speek = speekers[mood](mood);
        ///        console.write(Name + &quot;: &quot; + speek.Say);
        ///        return speek.Mood;
        ///    }
        ///
        ///    typedef Func&lt;Mood, Speek&gt; 		  Speeker; 
        ///    typedef Dictionary&lt;Mood, Speeker&gt; Speekers; 
        ///        
        ///    protected Speekers speekers = new Speekers();
        ///
        ///    protected virtual void initSpeekers()
        ///    {
        ///        Speeker  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LolCats {
            get {
                return ResourceManager.GetString("LolCats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var cats = new [] 
        ///{
        ///    new Lolcat(&quot;Kitty&quot;), 
        ///    new Lolcat(&quot;Furry Kitty&quot;), 
        ///    new Trollcat(&quot;Ball of Fur&quot;)
        ///};
        ///
        ///var mood = Mood.Nize;
        ///
        ///for(int i = 0; i &lt; 30; i++)
        ///{
        ///    int cat = random.Int(3);
        ///    mood = cats[cat].Say(mood);
        ///}
        ///
        ///console.write(&quot;Powered by speaklolcat.com&quot;);.
        /// </summary>
        public static string LolCatsApplication {
            get {
                return ResourceManager.GetString("LolCatsApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public enum Mood
        ///{
        ///    Nize,
        ///    Hungry,
        ///    Skerd,
        ///}
        ///
        ///public class Speek
        ///{
        ///    public string Say  { get; set; }
        ///    public Mood   Mood { get; set; }
        ///}
        ///
        ///public class Speeks
        ///{
        ///    static method AnySpeek(Mood mood)
        ///    {
        ///        Speek[] choices;
        ///        switch (mood)
        ///        {
        ///            case Mood.Nize: choices = NizeTalk; break;
        ///            case Mood.Skerd: choices = SkerdTalk; break;
        ///            default: choices = HungryTalk; break;
        ///        }
        ///        
        ///        return choices[random. [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LolCatsSpeek {
            get {
                return ResourceManager.GetString("LolCatsSpeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public class Trollcat : Lolcat
        ///{
        ///    public Trollcat(string name)
        ///        : base(name)
        ///    {
        ///    }
        ///
        ///    protected override void initSpeekers()
        ///    {
        ///        base.initSpeekers();
        ///
        ///        speekers[Mood.Nize] = function(mood)
        ///        {
        ///            return new Speek { Say = &quot;BAD KITTEH!&quot;, Mood = Mood.Skerd };
        ///        };
        ///
        ///        speekers[Mood.Hungry] = hungry;
        ///    }
        ///
        ///    function hungry(Mood m)
        ///    {
        ///        return new Speek { Say = &quot;NO CHEEZBURGER!&quot;, Mood = Mood.Skerd };
        ///    }
        ///}.
        /// </summary>
        public static string LolCatsTrollcat {
            get {
                return ResourceManager.GetString("LolCatsTrollcat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to class Misc 
        ///{
        ///    typedef IEnumerable&lt;int&gt; 	 Data;
        ///    typedef function&lt;int, int&gt;   Calculation;
        ///    typedef Dictionary&lt;int, int&gt; Results;
        ///
        ///    void main()
        ///    {
        ///        var data = [2, 3, 5, 7, 11];
        ///        var calc = function(int value)
        ///        {
        ///            return value*5;
        ///        };
        ///        
        ///        Results results = new Results();
        ///        calculate(data, calc, results);
        ///    }
        ///
        ///    private void calculate(Data data, Calculation fn, Results results)
        ///    {
        ///        foreach(var d in data)
        ///        {
        ///           [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Misc {
            get {
                return ResourceManager.GetString("Misc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public class Linker : ManagedLinker
        ///{
        ///    public SyntaxNode CheckCall(SyntaxNode node, SemanticModel model)
        ///    {
        ///        InvocationExpressionSyntax call   = (InvocationExpressionSyntax)node;
        ///        ISymbol                    caller = GetSemantics(model,  call.Expression);
        ///
        ///        bool isPure = false;
        ///        if (caller == null)
        ///            Error(call, &quot;cannot resolve &apos;&quot; + call.Expression.ToString() + &quot;&apos;&quot;);
        ///        else
        ///        {
        ///            ITypeSymbol callee = caller.ContainingType;
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PureLinker {
            get {
                return ResourceManager.GetString("PureLinker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public class Parser : ManagedParser&lt;Linker&gt;
        ///{
        ///    public SyntaxNode ParseClass(SyntaxNode node, string  id, ParameterListSyntax args)
        ///    {
        ///        IEnumerable&lt;SyntaxNode&gt; assigments = node
        ///            .DescendantNodes()
        ///            .OfType&lt;ExpressionStatementSyntax&gt;()
        ///            .Where(statement =&gt; IsAssigment(statement.Expression.CSharpKind()))
        ///            .Select(assignment =&gt; assignment.Expression);
        ///
        ///        IEnumerable&lt;SyntaxNode&gt; calls = node
        ///            .DescendantNodes()
        ///            .Of [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PureParser {
            get {
                return ResourceManager.GetString("PureParser", resourceCulture);
            }
        }
    }
}
